---
- hosts: maincomputer
  remote_user: root
  vars:
    username: shinichi
  tasks:
    - name: Install nVidia binary drivers, bumblebee
      apt: name={{ item }} state=present
      with_items:
        - nvidia-driver-390
        - bumblebee-nvidia  # installs bumblebee but in such a way that Mesa won't break
        - xserver-xorg-input-mouse
        - xserver-xorg-input-kbd

    - name: add {{ username }} to bumblebee group
      user:
        name: shinichi
        groups: bumblebee
        append: yes

    - name: bumblebee.conf force use nvidia driver
      lineinfile:
        path: /etc/bumblebee/bumblebee.conf
        regexp: '^Driver='
        line: 'Driver=nvidia'
        backup: no
      notify: systemctl restart bumblebeed

    - name: bumblebee.conf points to wrong directories for nvidia libraries.
      replace:
        path: /etc/bumblebee/bumblebee.conf
        regexp: 'nvidia-current'
        replace: 'x86_64-linux-gnu'
        backup: no
      notify: systemctl restart bumblebeed

    - name: bumblebee.conf XorgModulePath should look in /usr/lib/x86_64-linux-gnu/nvidia/xorg
      lineinfile:
        path: /etc/bumblebee/bumblebee.conf
        regexp: '^XorgModulePath'
        line: 'XorgModulePath=/usr/lib/x86_64-linux-gnu/nvidia/xorg,/usr/lib/xorg/modules'
        state: present
      notify: systemctl restart bumblebeed

    - name: copy xorg.conf.intelonly to /etc/X11/
      # This file points the X11 nvidia to the wrong PCI BusID, so you can rmmod nvidia kernel modules and echo OFF >> /proc/acpi/bbswitch while X11 is running
      # To use nVidia graphics, simply do not have a xorg.conf. gpu-manager will write to /usr/share/X11/xorg.conf.d/11-nvidia-prime.conf, which will automatically load nvidia, pushing intel graphics aside.
      # Do we still need bumblebee then? Well yes, for /proc/acpi/bbswitch.
      copy:
        src: files/xorg.conf.intelonly
        dest: /etc/X11/xorg.conf.intelonly
        owner: root
        group: root
        mode: 0644

  handlers:
    - name: systemctl restart bumblebeed
      shell: systemctl restart bumblebeed
