---
- hosts: maincomputer
  remote_user: root
  vars:
    username: shinichi
  tasks:
    - name: pacman -Syu
      pacman: 
        update_cache: yes
        upgrade: yes

    - name: Install Basics
      pacman: name={{ item }} state=latest
      with_items:
        - ansible
        - anki
        - bookworm
        - chromium
        - code  # OSS version of Visual Studio Code
        - cups-pdf  # print to pdf
        - emacs
        - feh
        - firefox
        - go
        - htop
        - hugo
        - i3
        - ideviceinstaller  # for managing iPhone apps
        - iftop
        - ifuse  # to mount iPhone app directories, USB Mass Storage
	- keepassxc
        - libimobiledevice-utils  # idevice_id, ideviceinfo, idevicepair (low level iOS utils)
        - mlocate
	- ncdu  # ncurses du for directories
	- newsboat  # RSS reader to avoid distraction
        - pamixer  # use pamixer instead of amixer to set volume on Manjaro/Arch
        - physlock  # the only screen locker that won't let you switch to VTs
        - powertop
        - quodlibet  # good replacement for fb2k
        - ranger
        - redshift
        - redshift-gtk
        - scrot
        - syncthing
        - veracrypt
        - virtualenvwrapper
        - zfs-utils  # need to install linux***-zfs/spl to actually get zfs working thogh

    - name: Create {{ username }}, ensure that he can sudo
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        groups: sudo

    # Validate the sudoers file before saving
    - name: ensure that {{ username }} can sudo without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^shinichi ALL='
        line: 'shinichi ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Customize keyboard Ctrl in X11
      # ctrl:nocaps because sometimes Caps Lock activates silently when I’m in the lockscreen
      # compose key is a Unix specific key that helps with inputting foreign language alphabets
      # I can’t believe ctrl-alt-backspace is optional
      lineinfile:
        path: /etc/X11/xorg.conf.d/00-keyboard.conf
        state: present
        regexp: 'Option "XkbOptions"'
        line: 'Option "XkbOptions" "compose:paus,terminate:ctrl_alt_bksp,ctrl:nocaps"'

    - name: Customize keyboard turn PrtSc key into Menu key (X11 only)
      # To get rid of the useless PrtSc key on the Thinkpad X230 keyboard. GDM will load ~/.Xmodmap automatically. If it were any other desktop manager I’d have to hack up a lot of scripts.
      lineinfile:
        path: /home/{{ username }}/.Xmodmap
        state: present
        create: yes
        line: 'keycode 107 = Menu'
      tags:
        - dotfiles

    - name: .bashrc should source .bash_profile
      lineinfile:
        path: /home/{{username}}/.bashrc
        state: present
        line: 'source ~/.bash_profile'
      tags:
        - dotfiles

    - name: utilities for i3 desktop
      apt: name={{ item }} state=latest
      with_items:
        - arandr  # a GUI to configure xrandr (very useful)
        - autorandr  # automatically switches between single/multi monitor when plugged/unplugged
        - udiskie  # automatically mounts new disks
        - lxappearance  # gtk engines: makes GTK apps beautiful outside of GTK environment

    - name: Install tlp to manage power
      pacman: name={{ item }} state=latest
      with_items:
        - tlp
        - acpi_call
      tags: tlp

    - name: tlp set battery thresholds
      blockinfile:
        path: /etc/default/tlp
        block: |
            START_CHARGE_THRESH_BAT0=70
            STOP_CHARGE_THRESH_BAT0=75
        insertafter: '# Main / Internal battery \(values in \%\)'
      tags: tlp

    - name: enable service tlp, tlp-sleep and ensure it is not masked
      systemd: name={{ item }} enabled=yes
        with_items:
         - tlp
         - tlp-sleep
      tags: tlp