# For software that I might not need in the future, but requires too much setup
---
- hosts: maincomputer
  remote_user: root
  vars:
    username: shinichi
  tasks:
    - name: Install docker
      pacman: name={{ item }} state=latest
      with_items:
      - docker
      - docker-compose
      tags: docker

    - name: add shinichi to docker group
      user:
        name: shinichi
        groups: docker
        append: yes
      tags: docker
