---
- hosts: maincomputer
  remote_user: root
  vars:
    username: shinichi
  tasks:
    - name: Install nVidia binary drivers, nvidia-prime
      apt: name={{ item }} state=present
      with_items:
        - nvidia-driver-390
        - nvidia-prime  # Ubuntu's useful scripts for switching between intel/nouveau and nvidia