- hosts: maincomputer
  remote_user: root
  tasks:
    # - name: create snapper config 'root' for /
    #   shell: snapper -c root create-config /

    - name: configure snapper's hourly snapshots
      lineinfile:
        path: /etc/snapper/configs/root
        regexp: '^TIMELINE_LIMIT_HOURLY'
        line: 'TIMELINE_LIMIT_HOURLY="5"'

    - name: configure snapper's weekly snapshots
      lineinfile:
        path: /etc/snapper/configs/root
        regexp: '^TIMELINE_LIMIT_WEEKLY'
        line: 'TIMELINE_LIMIT_WEEKLY="4"'

    - name: configure snapper's monthly snapshots
      lineinfile:
        path: /etc/snapper/configs/root
        regexp: '^TIMELINE_LIMIT_MONTHLY'
        line: 'TIMELINE_LIMIT_MONTHLY="3"'

    - name: configure snapper's yearly snapshots
      lineinfile:
        path: /etc/snapper/configs/root
        regexp: '^TIMELINE_LIMIT_YEARLY'
        line: 'TIMELINE_LIMIT_YEARLY="0"'

    - name: configure snapper storage space
      lineinfile:
        path: /etc/snapper/configs/root
        regexp: '^SPACE_LIMIT'
        line: 'SPACE_LIMIT="1.5"'

    - name: updatedb should not include /.snapshots directory
      lineinfile:
        path: /etc/updatedb.conf
        regexp: '^PRUNENAMES'
        line: PRUNENAMES=".snapshots"

    - name: enable snapper-timeline
      systemd:
        name: snapper-timeline
        enabled: yes
        state: started

    - name: enable snapper-cleanup
      systemd:
        name: snapper-cleanup
        enabled: yes
        state: started
